Added js/jquery-1.6.4.js and tried to use it and new function idMyGadget_js_alter in idMyGadget.module to fix the "Uncaught TypeError: a.mobile.document.on is not a function" JS console error we are seeing.  Apparently this is resolvable by adding a module that can manage multiple jQuery versions but at this point I would rather upgrade to Drupal 8, which uses jQuery 1.7 .  So frankly this is cruft but it is at least clearly labeled as such.  For more information, see js/readme.txt .